// Static guidance only. Session-specific medical content always comes from the API.
export const CLINICAL_NOTES = {
  scopeTitle: "Lưu ý về kết quả tư vấn",
  scope: "Kết quả không thay thế chẩn đoán hoặc điều trị của bác sĩ.",
  symptomHint: "Mô tả thời điểm bắt đầu, mức độ và các dấu hiệu đi kèm.",
  emergencyTitle: "Khi nào cần cấp cứu?",
  emergency: "Nếu có dấu hiệu nghiêm trọng hoặc tình trạng chuyển nặng nhanh, hãy liên hệ dịch vụ cấp cứu tại nơi bạn sống hoặc đến cơ sở y tế gần nhất.",
  priorityTitle: "Cần ưu tiên đánh giá tại cơ sở y tế",
  priority: "Kết quả ghi nhận dấu hiệu cần được ưu tiên đánh giá tại cơ sở y tế.",
  reasonTitle: "Vì sao chuyên khoa này được gợi ý?",
  departmentTitle: "Tìm hiểu về chuyên khoa",
  confidence: "Mức độ phù hợp không phải xác suất mắc bệnh.",
  confidenceTitle: "Hiểu về độ phù hợp",
  confidenceDetail: "Hãy đọc chỉ số này cùng phần giải thích của kết quả. Cơ sở y tế sẽ xác nhận chuyên khoa phù hợp sau khi đánh giá trực tiếp.",
  resultHint: "Chọn một kết quả để xem giải thích.",
  noReasoning: "Chưa có giải thích chi tiết cho kết quả này.",
  noAdditionalResults: "Chưa có kết quả tham khảo bổ sung cho lần tư vấn này.",
  distanceTitle: "Khoảng cách được tính thế nào?",
  distance: "Khoảng cách được tính từ vị trí của bạn đến cơ sở, không phải quãng đường di chuyển.",
  contactTitle: "Trước khi đến khám",
  contact: "Vui lòng liên hệ cơ sở để xác nhận thông tin trước khi đến.",
  noCoordinates: "Một số cơ sở chưa có vị trí trên bản đồ.",
  unavailableFacilities: "Cơ sở được gợi ý hiện không còn trong danh sách cơ sở đang hoạt động.",
};
